### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by kawpii** [matheuslessarodrigues/verco#26] opened 2020-05-12 12:25 UTC
Getting following error when trying to run verco inside a git repo

> memory allocation of 18446744073709551609 bytes failedAborted (core dumped)

additional info:

`$uname -a`

`Linux hostname 5.6.10-300.fc32.x86_64 #1 SMP Mon May 4 14:29:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vamolessa** [comment] 2020-05-14 15:05
Oh, wow! Do you remember what was the last action you made before getting this? `log`? `log count`? `commit selected`?

Was it an opensource repository? If not, do you mind compiling `verco` in debug mode and running it with backtrace enabled (`export RUST_BACKTRACE=1`)?

**Comment by kawpii** [comment] 2020-05-15 06:06
>  Do you remember what was the last action you made before getting this?

commit and push to master, even tried verco after doing log, it seems last git command used does not matter, see why? in the second answer below.

> Was it an opensource repository? If not, do you mind compiling verco in debug mode and running it with backtrace enabled (export RUST_BACKTRACE=1)?

Does not matter whether it is opensource or closed, **it seems issue occur in the repos where code base is relatively large.** Try running verco on https://github.com/igorwojda/android-showcase

**Comment by vamolessa** [comment] 2020-05-15 16:12
This issue seems to only happen on your machine as people alread complained that `log` is slown in large repos ([linux kernel](https://github.com/torvalds/linux) for instance which is 3GB in size). I've tested (`log`, `commit`, `push` all working) both repositories and could not reproduce your crash.

Maybe you can clone `verco` and run it in debug mode with `export RUST_BACKTRACE=1`? It would help a lot! Thanks

**Comment by kawpii** [comment] 2020-05-22 05:26
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', src/tui.rs:32:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: core::result::Result<T,E>::unwrap
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/result.rs:1003
  15: verco::tui::show_tui
             at src/tui.rs:32
  16: verco::main
             at src/main.rs:23
  17: std::rt::lang_start::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: std::rt::lang_start
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by vamolessa** [comment] 2020-05-22 13:50
Can you confirm a few more things?
- what shell were you using
- which commit hash was it?
- which command di you use to run it? Just `cargo run` or something else? Like, did you pipe anything into/out of it?

Thanks

**Comment by kawpii** [comment] 2020-05-22 14:38
`bash`

`ff442561cb8838976d3d3a997c9178d970253671` of [android-showcase](https://github.com/igorwojda/android-showcase) repo

1. cloned the repo
2. built the binary locally using `cargo run`
3.  copied built binary to path
4. navigated android-showcase repo
5. `RUST_BACKTRACE=1 verco >> err.txt`


**Additional note:** 

about 5th step: if I used `RUST_BACKTRACE=1 verco` but stacktrace flashes and make invisible. and prompt statement looked like below 
`Verco @ /home/user/.../android-showcase  help user@host:~/.../android-showcase$ `

and following portions of the above background looks purple
`Verco @ /home/user/.../android-showcase  help user@host `

and made next typing commands invisible.
(probably something have to do with `tui-rs`)

so I tried the command like in 5th step (redirecting to file), then I got the stack trace on the terminal but not saved in the err.txt. err.txt contained following `Verco @ /home/user/.../android-showcase  help user@host:~/.../android-showcase$ `

May be I am doing something wrong here.

**Comment by vamolessa** [comment] 2020-05-22 16:22
I could reproduce this error when running `verco >> err.txt`.
However, this seems expected since this is a tui program.
Maybe you could try `cargo run 2> err.txt`?

Also, I meant which verco commit hash you're testing on :)

**Comment by kawpii** [comment] 2020-05-23 06:01
> Maybe you could try cargo run 2> err.txt?
It run on your repo without any issues.

Verco commit hash: `b8caf10cde06532397c2d8d5ff321fe7911625c2`

**Comment by kawpii** [comment] 2020-05-23 07:07
It seems I found the issue. this panic only happens if terminal window is small, see [this screen record
](https://drive.google.com/open?id=11ycXPiRXZwWgOdA-psULclwQTbtnBCdV)

But if my terminal window is fullscreen there is no any panic as you can see in [this video](https://drive.google.com/open?id=1-i6-gwy0XM5Y_qABchDsoVo33hFDpril)

**Comment by kawpii** [comment] 2020-05-23 07:12
After further experimenting I found that if width of the terminal window is smaller than certain amount this panic occurs in some repositories.

https://github.com/fdehau/tui-rs/issues/177 : related to sudden clearing of the terminal screen after the panic.

**Comment by vamolessa** [comment] 2020-05-23 14:44
AH! I could see the stacktrace from the video!
`attempt to subtract with overflow tui_util.rs:96:13`
Gonna fix it and test with a small terminal window
Thanks!

**Comment by vamolessa** [comment] 2020-05-23 16:43
It should be fixed now. It's both updated on crates and github releases.

The terminal window size can still be too small for verco, tho. In that case, it will panic with a relevant error message.

Will close now. Thanks for your help!

**Closed as completed by vamolessa** 2020-05-23 16:43 UTC
Labels: bug

**Comment by kawpii** [comment] 2020-05-24 01:43
@matheuslessarodrigues 
Something else is broken, I tried to build the binary locally after recent commit getting following

```
$ RUST_BACKTRACE=1 cargo run build
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/verco build`
thread 'main' panicked at 'could not canonicalize path: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/repositories.rs:12:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: core::result::Result<T,E>::expect
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/result.rs:961
  15: verco::repositories::get_current_version_control
             at src/repositories.rs:12
  16: verco::main
             at src/main.rs:22
  17: std::rt::lang_start::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: std::rt::lang_start
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by vamolessa** [comment] 2020-05-25 14:18
If you want to run a rust application with cargo, you just have to `cargo run`.
By adding `build`, cargo will pass it as a string argument to the built application. In the case of verco, it tries to start in the folder `build` which does not exist.

I will improve the error messages to not look like crashes!

**Comment by kawpii** [comment] 2020-05-25 15:22
Sorry my mistake!
